name: Build

on: 
  push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Build-${{ github.run_number }}"
        prerelease: false
        files: |
          LICENSE
