name: Build

on: [push, workflow_dispatch]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    # copy-paste this part for however many packs you want to build
    - name: Build Pack
      uses: Sorrowfall/Resource-Packager@main
      with:
        name: AstronoPack # The name of the Resource Pack
        output-directory: build # What directory to save the Resource Pack in
        optimize-jsons: true # Whether or not to optimize JSON file
      # copy-paste down to here
    - uses: actions/checkout@v1
    - name: Publish Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Build-${{ github.run_number }}"
        prerelease: false
        files: |
          LICENSE
          build/AstronoPack.zip
